spring:
  application:
    name: redis-examples
  redis: # 以下为默认配置，可省略。不同时声明
    host: localhost
    port: 6379
    database: 0
  cache: # 整合cache redis。代码声明详细配置时无效
    redis:
      cache-null-values: true # 默认值，可省略。缓存空数据，避免缓存穿透
      time-to-live: 50000 # 单位毫秒，50秒
  jackson:
    default-property-inclusion: non_null # springmvc忽略空值属性


logging:
  level:
    root: warn
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
